import { motion, AnimatePresence } from "framer-motion";
import { MdClose } from "react-icons/md";

const badgeColor = (risk = "") => {
   switch (risk.toLowerCase()) {
      case "low":
         return "bg-green-500/10 text-green-400";

      case "medium":
         return "bg-yellow-500/10 text-yellow-400";

      case "high":
         return "bg-orange-500/10 text-orange-400";

      default:
         return "bg-red-500/10 text-red-400";
   }
};

const AIReportModal = ({
   open,
   onClose,
   report,
}) => {

   if (!open || !report) return null;

   return (

      <AnimatePresence>

         <motion.div

            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}

            className="
               fixed
               inset-0
               bg-black/70
               backdrop-blur-sm
               flex
               justify-center
               items-center
               z-50
               p-5
            "

         >

            <motion.div

               initial={{
                  scale: 0.95,
                  opacity: 0,
               }}

               animate={{
                  scale: 1,
                  opacity: 1,
               }}

               exit={{
                  scale: 0.95,
                  opacity: 0,
               }}

               className="
                  w-full
                  max-w-5xl
                  max-h-[90vh]
                  overflow-y-auto
                  rounded-2xl
                  bg-[#0B1220]
                  border
                  border-cyan-500/20
                  shadow-xl
               "

            >

               {/* Header */}

               <div className="flex justify-between items-center border-b border-white/10 p-6">

                  <div>

                     <h2 className="text-2xl font-bold text-white">
                        AI Analysis Report
                     </h2>

                     <p className="text-gray-400 text-sm mt-1">
                        Detailed forensic analysis generated by PharmaTrack AI
                     </p>

                  </div>

                  <button

                     onClick={onClose}

                     className="
                        w-10
                        h-10
                        rounded-lg
                        bg-red-500/10
                        text-red-400
                        hover:bg-red-500/20
                     "

                  >

                     <MdClose size={22} />

                  </button>

               </div>

               {/* Body */}

               <div className="p-6 space-y-8">

                    {/* Drug Information */}

                <section>

                <h3 className="text-lg font-semibold text-cyan-400 mb-4">
                    Drug Information
                </h3>

                <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">

                    <div className="bg-[#020817] rounded-xl p-4">
                        <p className="text-gray-400 text-sm">Drug Name</p>
                        <h4 className="text-white font-semibold mt-2">
                            {report.drug?.name || "N/A"}
                        </h4>
                    </div>

                    <div className="bg-[#020817] rounded-xl p-4">
                        <p className="text-gray-400 text-sm">Drug ID</p>
                        <h4 className="text-white font-semibold mt-2">
                            {report.drugId}
                        </h4>
                    </div>

                    <div className="bg-[#020817] rounded-xl p-4">
                        <p className="text-gray-400 text-sm">Batch Number</p>
                        <h4 className="text-white font-semibold mt-2">
                            {report.drug?.batchNumber || "N/A"}
                        </h4>
                    </div>

                    <div className="bg-[#020817] rounded-xl p-4">
                        <p className="text-gray-400 text-sm">Current Stage</p>
                        <h4 className="text-white font-semibold mt-2">
                            {report.currentStage}
                        </h4>
                    </div>

                    <div className="bg-[#020817] rounded-xl p-4">
                        <p className="text-gray-400 text-sm">Blockchain</p>
                        <h4 className={`font-semibold mt-2 ${
                            report.blockchainVerified
                            ? "text-green-400"
                            : "text-red-400"
                        }`}>
                            {report.blockchainVerified
                            ? "Verified"
                            : "Not Verified"}
                        </h4>
                    </div>

                    <div className="bg-[#020817] rounded-xl p-4">
                        <p className="text-gray-400 text-sm">Total Scans</p>
                        <h4 className="text-white font-semibold mt-2">
                            {report.totalScans}
                        </h4>
                    </div>

                </div>

                </section>

                  {/* Summary */}

                  <section>

                     <h3 className="text-lg font-semibold text-cyan-400 mb-3">
                        Summary
                     </h3>

                     <p className="text-gray-300 leading-7">
                        {report.summary}
                     </p>

                  </section>

                  {/* AI Result */}

                  <section>

                     <h3 className="text-lg font-semibold text-cyan-400 mb-4">
                        AI Result
                     </h3>

                     <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">

                        <div className="bg-[#020817] rounded-xl p-4">
                           <p className="text-gray-400 text-sm">Risk Score</p>
                           <h4 className="text-3xl text-white font-bold mt-2">
                              {report.riskScore}
                           </h4>
                        </div>

                        <div className="bg-[#020817] rounded-xl p-4">
                           <p className="text-gray-400 text-sm">Risk Level</p>

                           <span className={`mt-3 inline-block px-3 py-1 rounded-full text-sm ${badgeColor(report.riskLevel)}`}>
                              {report.riskLevel}
                           </span>
                        </div>

                        <div className="bg-[#020817] rounded-xl p-4">
                           <p className="text-gray-400 text-sm">Prediction</p>

                           <h4 className="text-xl text-white mt-2">
                              {report.prediction}
                           </h4>
                        </div>

                        <div className="bg-[#020817] rounded-xl p-4">
                           <p className="text-gray-400 text-sm">Confidence</p>

                           <h4 className="text-3xl text-white mt-2">
                              {report.confidence}%
                           </h4>
                        </div>

                        <div className="bg-[#020817] rounded-xl p-4">
                            <p className="text-gray-400 text-sm">
                                Anomaly Score
                            </p>

                            <h4 className="text-3xl text-white font-bold mt-2">
                                {report.anomalyScore}
                            </h4>
                        </div>

                        <div className="bg-[#020817] rounded-xl p-4">
                            <p className="text-gray-400 text-sm">
                                Total Anomalies
                            </p>

                            <h4 className="text-3xl text-white font-bold mt-2">
                                {report.totalAnomalies}
                            </h4>
                        </div>

                     </div>

                    

                  </section>

                  {/* Risk Factors */}

                  <section>

                     <h3 className="text-lg font-semibold text-cyan-400 mb-4">
                        Risk Factors
                     </h3>

                     <div className="space-y-3">

                        {report.riskFactors?.map((item, index) => (

                           <div

                              key={index}

                              className="
                                 bg-[#020817]
                                 rounded-xl
                                 p-4
                                 border border-cyan-500/10
                              "

                           >

                              <div className="flex justify-between">

                                 <h4 className="text-white font-semibold">
                                    {item.factor}
                                 </h4>

                                 <span
                                className={`px-3 py-1 rounded-full text-xs font-semibold ${
                                    item.severity === "Critical"
                                        ? "bg-red-500/10 text-red-400"
                                        : item.severity === "High"
                                        ? "bg-orange-500/10 text-orange-400"
                                        : item.severity === "Medium"
                                        ? "bg-yellow-500/10 text-yellow-400"
                                        : "bg-green-500/10 text-green-400"
                                }`}
                                >
                                {item.severity}
                                </span>

                              </div>

                              <p className="text-gray-400 mt-2">
                                 {item.description}
                              </p>

                           </div>

                        ))}

                     </div>

                  </section>

                  {/* AI Insights */}

                  <section>

                     <h3 className="text-lg font-semibold text-cyan-400 mb-4">
                        AI Insights
                     </h3>

                     <div className="space-y-3">

                        {report.insights?.map((item, index) => (

                           <div
                              key={index}
                              className="bg-[#020817] rounded-xl p-4"
                           >

                              <h4 className="text-white font-semibold">
                                 {item.type}
                              </h4>

                              <p className="text-gray-400 mt-2">
                                 {item.description}
                              </p>

                           </div>

                        ))}

                     </div>

                  </section>

                  {/* Recommendations */}

                  <section>

                     <h3 className="text-lg font-semibold text-cyan-400 mb-4">
                        Recommendations
                     </h3>

                     <div className="space-y-3">

                        {report.recommendations?.map((item, index) => (

                           <div

                              key={index}

                              className="bg-[#020817] rounded-xl p-4"

                           >

                              <div className="flex justify-between">

                                 <h4 className="text-white font-semibold">
                                    {item.title}
                                 </h4>

                               <span
                                className={`px-3 py-1 rounded-full text-xs font-semibold ${
                                    item.priority === "High"
                                        ? "bg-red-500/10 text-red-400"
                                        : item.priority === "Medium"
                                        ? "bg-yellow-500/10 text-yellow-400"
                                        : "bg-green-500/10 text-green-400"
                                }`}
                                >
                                {item.priority}
                                </span>

                              </div>

                              <p className="text-gray-400 mt-2">
                                 {item.description}
                              </p>

                           </div>

                        ))}

                     </div>

                  </section>

                  {/* Footer */}

                  <section className="border-t border-white/10 pt-6">

                     <div className="grid md:grid-cols-5 gap-4 text-sm">

                        <div>
                           <p className="text-gray-500">
                              Generated At
                           </p>

                           <p className="text-white mt-1">
                              {new Date(report.analyzedAt).toLocaleString()}
                           </p>

                        </div>

                        <div>
                           <p className="text-gray-500">
                              Processing Time
                           </p>

                           <p className="text-white mt-1">
                              {report.processingTime}
                           </p>

                        </div>

                        <div>
                           <p className="text-gray-500">
                              Model Version
                           </p>

                           <p className="text-white mt-1">
                              {report.modelVersion}
                           </p>

                        </div>

                        <div>
                            <p className="text-gray-500">
                                Analysis Source
                            </p>

                            <p className="text-white mt-1">
                                {report.analysisSource}
                            </p>
                        </div>

                        <div>
                            <p className="text-gray-500">
                                Status
                            </p>

                            <p className="text-green-400 mt-1 capitalize">
                                {report.status}
                            </p>
                        </div>

                     </div>

                  </section>

               </div>

            </motion.div>

         </motion.div>

      </AnimatePresence>

   );

};

export default AIReportModal;