import { motion } from "framer-motion";

import {
  MdChecklist,
  MdCheckCircle,
  MdWarningAmber,
  MdPriorityHigh,
} from "react-icons/md";

const defaultRecommendations = [];

const getPriority = (priority = "Low") => {
  switch (priority.toLowerCase()) {
    case "high":
      return {
        icon: MdPriorityHigh,
        badge: "bg-red-500/10 text-red-400",
        iconColor: "text-red-400",
      };

    case "medium":
      return {
        icon: MdWarningAmber,
        badge: "bg-yellow-500/10 text-yellow-400",
        iconColor: "text-yellow-400",
      };

    default:
      return {
        icon: MdCheckCircle,
        badge: "bg-green-500/10 text-green-400",
        iconColor: "text-green-400",
      };
  }
};

const RecommendationCard = ({
  recommendations = defaultRecommendations,
}) => {
  return (
    <motion.div
      whileHover={{ scale: 1.01 }}
      className="
            bg-[#0B1220]
            border border-cyan-500/20
            rounded-2xl
            p-6
            shadow-lg
         "
    >
      {/* Header */}

      <div className="flex items-center gap-3 mb-6">
        <div
          className="
                  w-12
                  h-12
                  rounded-xl
                  bg-green-500/10
                  flex
                  items-center
                  justify-center
               "
        >
          <MdChecklist
            size={26}
            className="text-green-400"
          />
        </div>

        <div>
          <h2
            className="
                     text-xl
                     font-bold
                     text-white
                  "
          >
            AI Recommendations
          </h2>

          <p
            className="
                     text-sm
                     text-gray-400
                  "
          >
            Suggested actions generated by AI
          </p>
        </div>
      </div>

      {/* Empty State */}

      {recommendations.length === 0 ? (
        <div className="text-center text-gray-400 py-12">
          No recommendations available.
        </div>
      ) : (
        <div className="space-y-4">
          {recommendations.map((item, index) => {
            const style = getPriority(item.priority);

            const Icon = style.icon;

            return (
              <motion.div
                key={index}
                whileHover={{
                  x: 4,
                }}
                className="
                              p-4
                              rounded-xl
                              bg-[#020817]
                              border
                              border-cyan-500/10
                              flex
                              items-start
                              gap-4
                           "
              >
                <div className="mt-1">
                  <Icon
                    size={24}
                    className={style.iconColor}
                  />
                </div>

                <div className="flex-1">
                  <div
                    className="
                                    flex
                                    items-center
                                    justify-between
                                 "
                  >
                    <h4
                      className="
                                       text-white
                                       font-semibold
                                    "
                    >
                      {item.title}
                    </h4>

                    <span
                      className={`
                                       px-3
                                       py-1
                                       rounded-full
                                       text-xs
                                       font-semibold
                                       ${style.badge}
                                    `}
                    >
                      {item.priority}
                    </span>
                  </div>

                  <p
                    className="
                                    text-gray-400
                                    text-sm
                                    mt-2
                                 "
                  >
                    {item.description}
                  </p>
                </div>
              </motion.div>
            );
          })}
        </div>
      )}
    </motion.div>
  );
};

export default RecommendationCard;